### ISSUE TITLE
Just updated and app crashed

### ISSUE THREAD

**Issue by DrunkMunki** [prom3theu5/iNGEN-Ark-RCON-Desktop#3]
Just updated to the latest and app crashed within 5mins, see below for log:
-On a side note are you able to put usernames in the chat log, its hard to see who says what

-----Application Exception Logged At: 26/08/2015 8:41:27 AM-----
Application Error Message:
An unhandled exception occurred: An error occurred while sending the request.

Error Stack Trace:
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SteamWeb.Client.<SendRequestAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SteamWeb.Client.<GetPlayerBansAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at iNGen.ViewModels.PlayersViewModel.<<UpdateSteamPlayerInfo>b__59_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at iNGen.ViewModels.PlayersViewModel.<UpdateSteamPlayerInfo>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at iNGen.ViewModels.PlayersViewModel.<<-ctor>b__49_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at iNGen.App.Main()
-----END OF ERROR-----

**Comment by prom3theu5** [comment]
Excellent. Thanks for this. It's my steam api pcl causing the issue. Most likely a rate limit on steams end. I'll get a fix sorted when I wake up.

Cheers

**Comment by prom3theu5** [comment]
New version Pushed. Hopefully will sort the issue. Admins will now need to grab their Steam API Key, and enter it in settings. There is a button to take you to the page next to the box for the key.

**Comment by ghost** [comment]
Sorry to say: I just had an app hang. The problem is, I can't find the log (shouldn't it be on the desktop? There's nothing in the apps log directory either.)

Here's the Windows event log:

> <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
> <System>
> <Provider Name="Application Hang" /> 
> <EventID Qualifiers="0">1002</EventID> 
> <Level>2</Level> 
> <Task>101</Task> 
> <Keywords>0x80000000000000</Keywords> 
> <TimeCreated SystemTime="2015-08-26T16:27:20.000000000Z" /> 
> <EventRecordID>2128</EventRecordID> 
> <Channel>Application</Channel> 
> <Computer>***</Computer> 
> <Security /> 
> </System>
> <EventData>
> <Data>iNGen.exe</Data> 
> <Data>3.22.0.0</Data> 
> <Data>db4</Data> 
> <Data>01d0dfdba57c4b68</Data> 
> <Data>4294967295</Data> 
> <Data>C:\Users\me\AppData\Local\iNGen\app-3.38\iNGen.exe</Data> 
> <Data>523b73b8-4c0f-11e5-9bc8-d43d7eaf7a7a</Data> 
> <Data /> 
> <Data /> 
> <Binary>54006F00700020006C006500760065006C002000770069006E0064006F0077002000690073002000690064006C00650000000000</Binary> 
> </EventData>
> </Event>

**Comment by prom3theu5** [comment]
It should be on the desktop yeah.
Well, Its on the desktop of the user running the application, so if you're running it as admin, it'll be on the local administrator accounts desktop.

Since the last patch I've had it running, with the auto connect for five minutes, and its not crashed yet :(
Did you install the last patch?

**Comment by DrunkMunki** [comment]
i'm going to close this because the issue has been resolved.
